import type { ActorSystem } from '../actor/actor-system';
import type { ToolDefinition } from '../actor/types';
import {
  createAgentTool,
  createFileReadTool,
  createFileWriteTool,
  createFileEditTool,
  createBashTool,
  createGlobTool,
  createGrepTool,
  createTaskCreateTool,
  createTaskUpdateTool,
  createTaskListTool,
  createTaskGetTool,
  createTaskStopTool,
  createTaskOutputTool,
  createSendMessageTool,
  createTeamCreateTool,
  createTeamDeleteTool,
  createAskUserQuestionTool,
  createEnterPlanModeTool,
  createExitPlanModeTool,
  createWebSearchTool,
  createWebFetchTool,
  createSleepTool,
  createTodoWriteTool,
  createMcpCallTool,
  createMcpListServersTool,
  createMcpListToolsTool,
  createSkillExecuteTool,
  createSkillListTool,
  createMemorySearchTool,
  createMemorySaveTool,
} from './index';

export function registerAllTools(actorSystem: ActorSystem): ToolDefinition[] {
  return [
    createAgentTool(actorSystem),
    createFileReadTool(),
    createFileWriteTool(),
    createFileEditTool(),
    createBashTool(),
    createGlobTool(),
    createGrepTool(),
    createTaskCreateTool(),
    createTaskUpdateTool(),
    createTaskListTool(),
    createTaskGetTool(),
    createTaskStopTool(actorSystem),
    createTaskOutputTool(),
    createSendMessageTool(actorSystem),
    createTeamCreateTool(actorSystem),
    createTeamDeleteTool(actorSystem),
    createAskUserQuestionTool(),
    createEnterPlanModeTool(),
    createExitPlanModeTool(),
    createWebSearchTool(),
    createWebFetchTool(),
    createSleepTool(),
    createTodoWriteTool(),
    createMcpCallTool(),
    createMcpListServersTool(),
    createMcpListToolsTool(),
    createSkillExecuteTool(),
    createSkillListTool(),
    createMemorySearchTool(),
    createMemorySaveTool(),
  ];
}
