import fs from 'node:fs'
import path from 'node:path'

const repoRoot = process.cwd()
const distDir = path.resolve(repoRoot, 'official-plugins/dist')
const manifestPath = path.join(distDir, 'release-manifest.json')
const pluginRoot = path.resolve(repoRoot, 'official-plugins')
const uploadOfficialDir = process.env.PLUGIN_UPLOAD_DIR
  ? path.resolve(process.env.PLUGIN_UPLOAD_DIR)
  : path.resolve(repoRoot, 'mtools-server/uploads/plugins/official')

if (!fs.existsSync(manifestPath)) {
  console.error('缺少 release-manifest.json，请先执行 pnpm official:build')
  process.exit(1)
}

const releaseManifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
const releases = Array.isArray(releaseManifest.releases) ? releaseManifest.releases : []
if (releases.length === 0) {
  console.error('无可发布的官方插件产物')
  process.exit(1)
}

fs.mkdirSync(uploadOfficialDir, { recursive: true })

function escapeSql(value) {
  return String(value).replaceAll("'", "''")
}

const sqlParts = []

for (const release of releases) {
  const slug = String(release.slug)
  const version = String(release.version)
  const zipName = String(release.zipName)
  const packageSha256 = String(release.packageSha256)
  const packageSizeBytes = Number(release.packageSizeBytes)

  const srcZipPath = path.join(distDir, zipName)
  if (!fs.existsSync(srcZipPath)) {
    console.error(`缺少 zip 文件: ${srcZipPath}`)
    process.exit(1)
  }

  const pluginDir = path.join(pluginRoot, slug)
  const pluginManifest = JSON.parse(
    fs.readFileSync(path.join(pluginDir, 'plugin.json'), 'utf8'),
  )
  const pluginName = String(pluginManifest.pluginName || slug)
  const pluginDescription = String(pluginManifest.description || '')
  const tag = String(pluginManifest.tag || '工具')

  const targetDir = path.join(uploadOfficialDir, slug)
  fs.mkdirSync(targetDir, { recursive: true })
  const targetZipPath = path.join(targetDir, `${version}.zip`)
  fs.copyFileSync(srcZipPath, targetZipPath)

  const packageFilePath = `plugins/official/${slug}/${version}.zip`

  sqlParts.push(`
INSERT INTO plugin_market_apps (
  slug, name, description, tag, version, status, installs, is_official, created_at, updated_at
) VALUES (
  '${escapeSql(slug)}',
  '${escapeSql(pluginName)}',
  '${escapeSql(pluginDescription)}',
  '${escapeSql(tag)}',
  '${escapeSql(version)}',
  'published',
  0,
  TRUE,
  NOW(),
  NOW()
)
ON CONFLICT (slug)
DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tag = EXCLUDED.tag,
  version = EXCLUDED.version,
  is_official = TRUE,
  status = 'published',
  updated_at = NOW();

INSERT INTO plugin_market_releases (
  app_id, version, package_file_path, package_sha256, package_size_bytes, status, created_at, updated_at
)
SELECT
  a.id,
  '${escapeSql(version)}',
  '${escapeSql(packageFilePath)}',
  '${escapeSql(packageSha256)}',
  ${Number.isFinite(packageSizeBytes) ? packageSizeBytes : 0},
  'published',
  NOW(),
  NOW()
FROM plugin_market_apps a
WHERE a.slug = '${escapeSql(slug)}'
ON CONFLICT (app_id, version)
DO UPDATE SET
  package_file_path = EXCLUDED.package_file_path,
  package_sha256 = EXCLUDED.package_sha256,
  package_size_bytes = EXCLUDED.package_size_bytes,
  status = 'published',
  updated_at = NOW();

UPDATE plugin_market_apps a
SET
  current_release_id = r.id,
  version = '${escapeSql(version)}',
  updated_at = NOW()
FROM plugin_market_releases r
WHERE a.slug = '${escapeSql(slug)}'
  AND r.app_id = a.id
  AND r.version = '${escapeSql(version)}';
`)
}

const sql = `-- Auto generated by scripts/official-publish.mjs\nBEGIN;\n${sqlParts.join('\n')}\nCOMMIT;\n`
const sqlPath = path.join(distDir, 'publish.sql')
fs.writeFileSync(sqlPath, sql, 'utf8')

console.log(`官方插件发布产物已复制到: ${uploadOfficialDir}`)
console.log(`请执行 SQL: ${sqlPath}`)
